gcp:
  type: POSTGRES_12
  databaseName: spre-subsumsjon
kafkaPool: nav-prod
kafkaResetPolicy: earliest
minReplicas: 24
maxReplicas: 24
env:
  - name: SUBSUMSJON_TOPIC
    value: flex.omrade-helse-etterlevelse
