gcp:
  type: POSTGRES_12
  databaseName: spre-subsumsjon
kafkaPool: nav-prod
kafkaResetPolicy: earliest
minReplicas: 0
maxReplicas: 0
diskAutoResize: true
env:
  - name: SUBSUMSJON_TOPIC
    value: flex.omrade-helse-etterlevelse
