kafkaPool: nav-prod
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/prod/srvsprearbeidsgiver
env:
- name: KAFKA_PREFER_ON_PREM
  value: "true"
- name: KAFKA_BOOTSTRAP_SERVERS
  value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
- name: KAFKA_RESET_POLICY
  value: none
- name: KAFKA_RAPID_TOPIC
  value: helse-rapid-v1
- name: KAFKA_CONSUMER_GROUP_ID
  value: spre-arbeidsgiver-v1
