strategy: Recreate
kafkaPool: nav-dev
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/dev/srvspreoppgaver
env:
- name: DATABASE_HOST
  value: b27dbvl013.preprod.local
- name: DATABASE_PORT
  value: "5432"
- name: DATABASE_NAME
  value: spre-oppgaver
- name: VAULT_MOUNTPATH
  value: postgresql/preprod-fss/
