strategy: Recreate
kafkaPool: nav-prod
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/prod/srvspreoppgaver
env:
- name: DATABASE_HOST
  value: a01dbvl011.adeo.no
- name: DATABASE_PORT
  value: "5432"
- name: DATABASE_NAME
  value: spre-oppgaver
- name: VAULT_MOUNTPATH
  value: postgresql/prod-fss/
