kafkaPool: nav-prod
ingresses:
- https://spre-gosys.nais.adeo.no
- https://spre-gosys.prod-fss.nais.io
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/prod/srvspregosys
env:
- name: KAFKA_PREFER_ON_PREM
  value: "true"
- name: KAFKA_BOOTSTRAP_SERVERS
  value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
- name: KAFKA_RAPID_TOPIC
  value: helse-rapid-v1
- name: KAFKA_CONSUMER_GROUP_ID
  value: spre-gosys-v1
- name: KAFKA_RESET_POLICY
  value: none
- name: KAFKA_MAX_RECORDS
  value: "50"
- name: KAFKA_MAX_POLL_INTERVAL_MS
  value: "500000"
- name: STS_URL
  value: http://security-token-service.default.svc.nais.local
- name: JOARK_BASE_URL
  value: https://dokarkiv.nais.adeo.no

