apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-sykepenger-saksbehandlingsstatistikk
  namespace: tbd
  labels:
    team: tbd
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 2
    retentionBytes: -1
    retentionHours: 2200
  acl:
    - team: tbd
      application: spre-saksbehandlingsstatistikk
      access: readwrite
    - team: ptsak
      application: pt-sak-sykepenger
      access: read
