apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-sykepenger-saksbehandlingsstatistikk
  namespace: tbd
  labels:
    team: tbd
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 2
    retentionBytes: -1
    retentionHours: 2201
  acl:
    - team: tbd
      application: spre-saksbehandlingsstatistikk
      access: readwrite
    - team: ptsak
      application: pt-sak-sykepenger-dev
      access: read
    - team: ptsak
      application: pt-sak-sykepenger-preprod
      access: read
