apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: temp-dokumenter-v4
  namespace: tbd
  labels:
    team: tbd
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 2
    retentionBytes: -1
    retentionHours: 168
  acl:
    - team: tbd
      application: spill-av
      access: readwrite
    - team: tbd
      application: spre-saksbehandlingsstatistikk
      access: read
