kafkaPool: nav-dev
gcp:
  type: POSTGRES_12
  databaseName: spre-saksbehandlingsstatistikk
kafkaConsumerGroup: tbd-spre-saksbehandlingsstatistikk-v4
kafkaResetPolicy: earliest
env:
  - name: KAFKA_EXTRA_TOPIC
    value: tbd.temp-dokumenter-v1
  - name: GIT_SHA
    value: "{{ git_sha }}"