kafkaPool: nav-dev
gcp:
  type: POSTGRES_12
  databaseName: spre-saksbehandlingsstatistikk
env:
- name: DUMMY
  value: "it works"
kafkaConsumerGroup: tbd-spre-saksbehandlingsstatistikk-v2
kafkaResetPolicy: earliest