name: Aiven-config

on:
  push:
    branches:
    - main
    paths:
    - 'config/saksbehandlingsstatistikk/aiven-dev.yml'
    - 'config/saksbehandlingsstatistikk/aiven-temp-dokumenter.yml'

jobs:
  deployDev:
    name: apply kafka-topic i dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: config/saksbehandlingsstatistikk/aiven-dev.yml,config/saksbehandlingsstatistikk/aiven-temp-dokumenter.yml
